apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-rona
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-docker-python-rhtap-three-component-scenarios-rona
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-docker-python-rhtap-three-component-scenarios-rona
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-rona
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-rona
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ebop-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-rona@sha256:9783c6684d4ee9fdf459e417dec505bba0d99148815ebc6cce1afc9100975640
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
